apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wachd-agent.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wachd-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  WACHD_WEBHOOK_SECRET: {{ .Values.wachd.webhookSecret | quote }}
