{{- if not .Values.wachd.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wachd-agent.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wachd-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  WACHD_WEBHOOK_SECRET: {{ required "wachd.webhookSecret is required when wachd.existingSecret is not set" .Values.wachd.webhookSecret | quote }}
{{- end }}
