apiVersion: v1
kind: Service
metadata:
  name: {{ include "wachd.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wachd.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wachd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
