{{- if .Values.worker.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wachd.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wachd.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "wachd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
